### ISSUE TITLE
[Bug]: The STREAMLIT_GATHER_USAGE_STATS environment variable is the wrong one

### ISSUE THREAD

**Issue by thomas-lamure** [deeplime-io/onecode#9]
### Version (tag/commit sha)

bb4b24ca2539c9539ea8ba3b5d39cfbc6f9a2448

### OS

Linux

### Profile

- [X] Expert
- [X] Tech-Savvy
- [X] Developer

### Problem description

In the [Streamlit documentation](https://docs.streamlit.io/library/advanced-features/configuration), the configuration example : 

```bash
export STREAMLIT_SERVER_PORT=80
```
corresponds to
```toml
[server]
port = 80
```

It is composed from a `STREAMLIT_` prefix, then the group `SERVER_`, then the parameter `PORT`

The `gatherUsageStats` parameter is in the group `[browser]`
```toml
[browser]
gatherUsageStats = false
```
So it should be converted to the env variable:
```
STREAMLIT_BROWSER_GATHER_USAGE_STATS
```

so in `onecode/cli/start.py`:

```py
os.environ['STREAMLIT_GATHER_USAGE_STATS'] = '0'
``` 
should be
```py
os.environ['STREAMLIT_BROWSER_GATHER_USAGE_STATS'] = 'false'
```

### What happened ?

When running
```bash
onecode-start
```
this log appears
```
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
```

### What should have happened

The program should start without displaying this line.

**Comment by theweaklink** [comment]
Good catch, thanks. Indeed the env var name is `STREAMLIT_BROWSER_GATHER_USAGE_STATS`

In terms of `0/false`, `1/true` there shouldn't be any difference

**Comment by theweaklink** [comment]
PR has been merged, closing issue
@thomas-lamure Feel free to re-open the issue if you notice something different on your end
